### ISSUE TITLE
MetaMask RPC error with own contract

### ISSUE THREAD

**Issue by Kevin-Mok** [application-research/fevm-nft-frontend#1]
I deployed my own fevm-nft-estuary contract at [0xBdf706E079b557353fA2d7ffE94e3Aa56f2E8d41](https://explorer.glif.io/address/0xBdf706E079b557353fA2d7ffE94e3Aa56f2E8d41/?network=wallaby). But when I replace the `const ERC721` with this address and the `const ERC721ABI` with the `abi` from `build/contracts/Estuary721.json` I compiled with Truffle, I'm getting this in the browser console when I try to click the "Mint" button after connecting my wallet:
```
MetaMask - RPC Error: Internal JSON-RPC error. 
Object { code: -32603, message: "Internal JSON-RPC error.", data: {…} }
code: -32603
data: Object { code: 1, message: "message execution failed: 
exit 33, reason: message failed with backtrace:\n00: f02038 
(method 2) -- contract reverted (33)\n (RetCode=33)" }
message: "Internal JSON-RPC error."
<prototype>: Object { … }
inpage.js:1:54366
```
I also tried keeping the `ERC721ABI` the same as yours just with my `ERC721` address since the ABI should be the same, but I'm still getting the same error. Do you have any idea what could be causing this? I pushed my code to [a branch in my fork](https://github.com/Kevin-Mok/fevm-nft-frontend/tree/my-contract) for reference.

**Comment by alvin-reyes** [comment]
Means the ABI is not compatible. Do you have a branch that I can look at? Also, remix can be a bit clunky. When you copy an ABI, make sure you select the proper contract on the drop down list.

**Comment by Kevin-Mok** [comment]
I mentioned that I used the `abi` from `build/contracts/Estuary721.json` I compiled with Truffle and also linked [a branch in the issue](https://github.com/Kevin-Mok/fevm-nft-frontend/tree/my-contract). :stuck_out_tongue:

**Comment by alvin-reyes** [comment]
did you set a price on the contract? I tried paying 1 TFIL and it worked. :)

https://explorer.glif.io/address/0xBdf706E079b557353fA2d7ffE94e3Aa56f2E8d41/?network=wallaby

Set it here (i know, I'll clean up the code). :) 

https://github.com/Kevin-Mok/fevm-nft-frontend/blob/c7ef7bcf0c6e357c2b3ce588d0456e18e74f25fa/src/views/Home/Body.js#L133

**Comment by Kevin-Mok** [comment]
I just set `publicPrice` to 1, and I was able to mint. How did you get your price to be 0? It seems weird that I can't set it to be any decimal value either.

Edit: Oh, is it because [`_publicSalePrice` is set to 1](https://github.com/application-research/fevm-nft-estuary/blob/1b3d257186b411f95aec0ed8d3d14a692f633b5d/contracts/Estuary721.sol#L19) in `Estuary721.sol` and [`requiredAmount = qty * _publicSalePrice`](https://github.com/application-research/fevm-nft-estuary/blob/1b3d257186b411f95aec0ed8d3d14a692f633b5d/contracts/Estuary721.sol#L54)?

**Comment by alvin-reyes** [comment]
Yes. :) Set that to 0 and it's going to be free mint. :)
